name: mcr
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2021.10.8=ha878542_0
  - certifi=2021.10.8=py37h89c1867_1
  - cudatoolkit=10.1.243=h6bb024c_0
  - curl=7.71.1=h8f29fe8_2
  - expat=2.4.1=h9c3ff4c_0
  - freetype=2.10.4=h5ab3b9f_0
  - gettext=0.19.8.1=hf34092f_1004
  - git=2.32.0=pl5262hc120c5b_1
  - icu=68.1=h2531618_0
  - intel-openmp=2021.3.0=h06a4308_3350
  - jpeg=9d=h7f8727e_0
  - krb5=1.19.2=hcc1bbae_0
  - lcms2=2.12=h3be6417_0
  - libcurl=7.71.1=h303737a_2
  - libedit=3.1.20210714=h7f8727e_0
  - libevent=2.1.10=hcdb4288_3
  - libffi=3.2.1=hf484d3e_1007
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.16=h516909a_0
  - libpng=1.6.37=hbc83047_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtiff=4.2.0=h85742a9_0
  - libwebp-base=1.2.0=h27cfd23_0
  - lz4-c=1.9.3=h295c915_1
  - mkl=2021.3.0=h06a4308_520
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.0=py37h42c9631_2
  - mkl_random=1.2.2=py37h51133e4_0
  - ncurses=6.2=he6710b0_1
  - ninja=1.10.2=hff7bd54_1
  - numpy-base=1.21.2=py37h79a1101_0
  - olefile=0.46=py37_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=1.1.1l=h7f8727e_0
  - pcre2=10.35=h14c3975_1
  - perl=5.32.1=0_h7f98852_perl5
  - pip=21.2.2=py37h06a4308_0
  - pkg-config=0.29.2=h1bed415_8
  - python=3.7.1=h0371630_7
  - python_abi=3.7=2_cp37m
  - pytorch=1.6.0=py3.7_cuda10.1.243_cudnn7.6.3_0
  - readline=7.0=h7b6447c_5
  - setuptools=58.0.4=py37h06a4308_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - tmux=3.1=h1c4e50f_0
  - torchvision=0.7.0=py37_cu101
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==0.14.0
    - attrs==21.2.0
    - backcall==0.2.0
    - blessings==1.7
    - blis==0.4.1
    - boto3==1.18.63
    - botocore==1.21.63
    - cached-property==1.5.2
    - cachetools==4.2.2
    - catalogue==1.0.0
    - charset-normalizer==2.0.6
    - click==8.0.1
    - cloudpickle==2.0.0
    - codecov==2.1.12
    - coverage==5.5
    - cycler==0.10.0
    - cymem==2.0.5
    - cython==0.29.20
    - cytoolz==0.11.0
    - decorator==5.1.0
    - dill==0.3.4
    - en-core-web-sm==2.3.0
    - fake-useragent==0.1.11
    - filelock==3.0.12
    - future==0.18.2
    - fvcore==0.1.5.post20210915
    - google-auth==1.35.0
    - google-auth-oauthlib==0.4.6
    - gpustat==0.4.1
    - grpcio==1.40.0
    - h5py==3.4.0
    - hyperopt==0.1.2
    - icu-tokenizer==0.0.1
    - idna==3.2
    - importlib-metadata==4.8.1
    - importlib-resources==5.4.0
    - iniconfig==1.1.1
    - iopath==0.1.9
    - ipdb==0.13.9
    - ipython==7.27.0
    - jedi==0.18.0
    - jinja2==3.0.2
    - jmespath==0.10.0
    - joblib==1.0.1
    - jsonschema==4.2.1
    - keras==2.6.0
    - kiwisolver==1.3.2
    - markdown==3.3.4
    - markupsafe==2.0.1
    - matplotlib==3.4.3
    - matplotlib-inline==0.1.3
    - msgpack==1.0.2
    - murmurhash==1.0.5
    - networkx==2.6.3
    - nltk==3.6.2
    - numpy==1.19.0
    - nvidia-ml-py3==7.352.0
    - oauthlib==3.1.1
    - opencv-python==4.5.4.58
    - packaging==21.0
    - pandas==1.3.3
    - parso==0.8.2
    - pathy==0.6.0
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==6.2.2
    - plac==1.1.3
    - pluggy==1.0.0
    - portalocker==2.3.2
    - prefetch-generator==1.0.1
    - preshed==3.0.5
    - prompt-toolkit==3.0.20
    - protobuf==3.18.0
    - psutil==5.8.0
    - ptyprocess==0.7.0
    - py==1.10.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydantic==1.8.2
    - pygments==2.10.0
    - pyicu==2.7.4
    - pymongo==3.12.0
    - pyparsing==2.4.7
    - pyrsistent==0.18.0
    - pytest==6.2.5
    - pytest-cov==2.12.1
    - python-dateutil==2.8.2
    - pytz==2021.1
    - pyyaml==5.4.1
    - ray==1.8.0
    - redis==3.5.3
    - regex==2021.8.28
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - s3transfer==0.5.0
    - sacremoses==0.0.45
    - scikit-learn==0.23.2
    - scipy==1.5.4
    - sentencepiece==0.1.91
    - smart-open==5.2.1
    - spacy==2.3.0
    - spacy-legacy==3.0.8
    - srsly==1.0.5
    - tabulate==0.8.9
    - tensorboard==2.6.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - termcolor==1.1.0
    - thinc==7.4.1
    - threadpoolctl==2.2.0
    - tokenizers==0.9.3
    - toml==0.10.2
    - toolz==0.11.1
    - tqdm==4.38.0
    - traitlets==5.1.0
    - transformers==3.5.1
    - typer==0.4.0
    - typing-extensions==3.10.0.2
    - urllib3==1.26.6
    - wasabi==0.8.2
    - wcwidth==0.2.5
    - werkzeug==2.0.1
    - yacs==0.1.8
    - zipp==3.5.0
prefix: /home/wh.347426/miniconda3/envs/mcr
